version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-cloud-storage
    versions:
    - 1.35.0
    - 1.35.1
    - 1.36.0
    - 1.36.1
    - 1.36.2
    - 1.37.0
    - 1.37.1
